name: vepkar_audio
description: Dictionary of the Livvi dialect of the Karelian language with audio files.

# Prevent publishing to pub.dev
publish_to: 'none'

# App version
version: 1.0.5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/dict.json
    - assets/audio/
    - assets/logo_about.png

  fonts:
     - family: Centro
       fonts:
         - asset: fonts/PFCentroSlabPro-Medium.ttf
     - family: Open Sans
       fonts:
         - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf